POST http://localhost:8080/users
Content-Type: application/json

{
    "name":"Felipe Maela",
    "username":"felipemaela04"
}

###
GET http://localhost:8080/users

###
GET http://localhost:8080/users/ad325a5b-571a-47e2-8c32-da1805fe1461

###
PUT http://localhost:8080/users/
Content-Type: application/json

{
    "name":"Felipe Nyusi",
    "username":"nyusi"
}

###
DELETE http://localhost:8080/users/7a487300-59bc-4993-897a-ac5bb4a01316